name: dbt_warehouse
version: '1.0.0'

profile: snowflake_warhouse

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  # Builds seeds into '<your_schema_name>_raw'
  dbt_warehouse:
    +schema: raw

models:
  dbt_warehouse:
    +static_analysis: strict
    raw:
      +materialized: incremental
      +incremental_strategy: append
      +schema: raw
    staging:
      +materialized: view
      +schema: stage
    marts:
      +materialized: incremental
      +incremental_strategy: merge
      +schema: mart