SELECT
    C_CUSTOMER_ID AS CUSTOMER_ID,
    C_SALUTATION AS SALUTATION,
	C_FIRST_NAME AS FIRST_NAME,
	C_LAST_NAME AS LAST_NAME,
	C_PREFERRED_CUST_FLAG AS PREFERRED_CUST_FLAG,
	C_BIRTH_DAY AS BIRTH_DAY,
	C_BIRTH_MONTH AS BIRTH_MONTH,
	C_BIRTH_YEAR AS BIRTH_YEAR,
	C_BIRTH_COUNTRY AS BIRTH_COUNTRY,
	C_LOGIN AS LOGIN,
	C_EMAIL_ADDRESS AS EMAIL_ADDRESS,
	C_LAST_REVIEW_DATE AS LAST_REVIEW_DATE,
    CURRENT_TIMESTAMP AS ODS_LOAD_TIME
FROM {{ source('TPCDS_SF100TCL','CUSTOMER') }}
WHERE C_BIRTH_YEAR >= {{ var("start_year") }}
    AND C_BIRTH_YEAR <  {{ var("end_year") }}
{% if is_incremental() %}
    AND C_LAST_REVIEW_DATE >= '{{ var("start_date","1900-01-01") }}'
    AND C_LAST_REVIEW_DATE <  '{{ var("end_date", "2999-01-01") }}'
{% endif %}