SELECT
    C_CUSTOMER_ID AS CUSTOMER_ID,
    C_SALUTATION AS SALUTATION,
	C_FIRST_NAME AS FIRST_NAME,
	C_LAST_NAME AS LAST_NAME,
	C_PREFERRED_CUST_FLAG AS PREFERRED_CUST_FLAG,
	C_BIRTH_DAY AS BIRTH_DAY,
	C_BIRTH_MONTH AS BIRTH_MONTH,
	C_BIRTH_YEAR AS BIRTH_YEAR,
	C_BIRTH_COUNTRY AS BIRTH_COUNTRY,
	C_LOGIN AS LOGIN,
	C_EMAIL_ADDRESS AS EMAIL_ADDRESS,
	D.D_DATE AS LAST_REVIEW_DATE,
	E.D_DATE AS FIRST_SALES_DATE,
	F.D_DATE AS FIRST_SHIPTO_DATE,
    CURRENT_TIMESTAMP AS ODS_LOAD_TIME
FROM 
	{{ source('TPCDS_SF100TCL','CUSTOMER') }} C
LEFT JOIN 
	{{ source('TPCDS_SF100TCL','DATE_DIM') }} D
		ON C.C_LAST_REVIEW_DATE = D.D_DATE_SK
LEFT JOIN 
	{{ source('TPCDS_SF100TCL','DATE_DIM') }} E
		ON C.C_FIRST_SALES_DATE_SK = E.D_DATE_SK
LEFT JOIN 
	{{ source('TPCDS_SF100TCL','DATE_DIM') }} F
		ON C.C_FIRST_SHIPTO_DATE_SK = F.D_DATE_SK
WHERE 
	E.D_DATE >= '{{ var("start_date","1900-01-01") }}'
    AND E.D_DATE <  '{{ var("end_date", "2999-01-01") }}'
